Repository sendgrid/smtpapi-ruby, pull requests merged in 2018-10, with the labels that each got.

#64 Resolve linting issues.
  .rubocop.yml
  LICENSE.txt
  examples/example.rb
  lib/smtpapi.rb
  lib/smtpapi/version.rb
  smtpapi.gemspec
  test/test.rb
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved, status: ready for deploy

#67 Add Use Cases directory
  use_cases/README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: sendgrid enhancement

#69 Remove duplicate text in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update
